// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYqGPqQ7yL84hCYIf1pDHURrNUAmY9hSQ',
    appId: '1:381278712395:web:b50b35a340016a362b53ce',
    messagingSenderId: '381278712395',
    projectId: 'sistlink-39ae5',
    authDomain: 'sistlink-39ae5.firebaseapp.com',
    storageBucket: 'sistlink-39ae5.firebasestorage.app',
    measurementId: 'G-FCHBPZV45S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTDaVOLzPO7EBEh20uQCS07sUZWmrPCJQ',
    appId: '1:381278712395:android:1ee3af899639d8162b53ce',
    messagingSenderId: '381278712395',
    projectId: 'sistlink-39ae5',
    storageBucket: 'sistlink-39ae5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeINFpR2RtTpcMqPNftx64Rsr_5fSHvSM',
    appId: '1:381278712395:ios:b5e8bf9fcab9aea82b53ce',
    messagingSenderId: '381278712395',
    projectId: 'sistlink-39ae5',
    storageBucket: 'sistlink-39ae5.firebasestorage.app',
    iosBundleId: 'com.example.sistLink1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeINFpR2RtTpcMqPNftx64Rsr_5fSHvSM',
    appId: '1:381278712395:ios:b5e8bf9fcab9aea82b53ce',
    messagingSenderId: '381278712395',
    projectId: 'sistlink-39ae5',
    storageBucket: 'sistlink-39ae5.firebasestorage.app',
    iosBundleId: 'com.example.sistLink1',
  );
}
